env: mysql
MySigningKey: "ASKDFJNTvjsnvsnsls"
redis:
  dns: "redis:6379"
  exp: 200
postgresDNS: "host=localhost user=root dbname=movie password=root sslmode=disable port=5432 TimeZone=Europe/Paris"
mysqlDNS: "root:@(127.0.0.1:3306)/movie"