version: '3.1'

services: 
  db:
    image: postgres:13.1-alpine
    restart: always
    environment: 
      POSTGRES_PASSWORD: example
      POSTGRES_USER: laposte
      POSTGRES_DB: movie
    network_mode: host
  
  redis:
    image: redis:6.0.9-alpine
    network_mode: host

  api:
    image: movie-api:v0.0.2
    command: ["sh", "-c", "sleep 10 && ./api_movie"]
    network_mode: host