version: '3.1'

services: 
  db:
    image: postgres:13.1-alpine
    restart: always
    environment: 
      POSTGRES_PASSWORD: example
      POSTGRES_USER: lapost
      POSTGRES_DB: movie
    ports:
      - 5432:5432
  
  redis:
    image: redis:6.0.9-alpine
    ports: 
      - 6379:6379