version: '3.1'

services: 
  db:
    image: postgres:13.1-alpine
    restart: always
    environment: 
      POSTGRES_PASSWORD: example
      POSTGRES_USER: laposte
      POSTGRES_DB: movie
    ports:
      - 5432:5432
  
  redis:
    image: redis:6.0.9-alpine
    ports: 
      - 6379:6379

  api:
    image: movie-api:v0.0.9
    command: ["sh", "-c", "sleep 10 && ./api_movie"]
    ports:
      - 8080:8080
    